name: Convert Markdown

on:
  push:
    paths:
      - "*.md"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Convert Markdown to PDF & HTML
        uses: mandarons/markdown-to-pdf-and-html@v1.0.2
        with:
          images_dir: images
          input_path: "./"
          output_pdf: "pdf"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: converted-docs
          path: |
            pdf
